all:
  hosts:
        web-1:
      ansible_host: 51.250.75.145
      fqdn: fhmfl2l507fg9bede8nq.auto.internal
        web-2:
      ansible_host: 158.160.50.199
      fqdn: fhm7gmnickodbb8n0rha.auto.internal
        main:
      ansible_host: 51.250.73.225
      fqdn: fhmjkm258c0ouc050fj6.auto.internal
        replica:
      ansible_host: 62.84.126.18
      fqdn: fhmvi8dvk6e6975can9u.auto.internal
        storage:
      ansible_host: 51.250.87.220
      fqdn: fhm5u41mb91p931mifki.auto.internal
      vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
